%董波 2014年11月6日
%获取调用函数时的日期，以字符串形式返回

function s_datetime = db_gaindatestring()

d_time = clock();

%按照年、月、日、时、分、秒做字符串回传
s_datetime = [num2str(d_time(1)),'年',...
    num2str(d_time(2)),'月',...
    num2str(d_time(3)),'日',...
    num2str(d_time(4)),'时',...
    num2str(d_time(5)),'分',...
    num2str(d_time(6)),'秒'];